"""First EDA over the ingested data — prints a markdown report to stdout.

Covers what the mentor asked for (2026-07-12): descriptive statistics,
corpus size, keyword frequencies, and the min/max feature analysis that
feeds the Gaussian Process threshold design. stdlib + psycopg only.

Run:  set -a; source .env; set +a
      python -m eda.ingest_overview > eda/reports/$(date +%F)_ingest_eda.md
"""

import os
import re
from collections import Counter

import psycopg

STOP = set("""a an the and or of to in for on at by with from as is are was were be been
being this that these those it its their his her they he she we you i not no but if then
than so such can could will would may might must shall should have has had do does did
about into over under after before during between out up down off above below more most
other some any all each both few own same only very s t just don now new says said say
bank banks banking financial finance group inc corp corporation company co shares stock
stocks share price target rating analyst analysts research report reports quarterly
q1 q2 q3 q4 2025 2026 nyse nasdaq""".split())

RISK_LEXICON = ["fine", "fines", "penalty", "lawsuit", "probe", "investigation",
                "consent order", "enforcement", "downgrade", "layoff", "layoffs",
                "loss", "losses", "fraud", "default", "distress", "outflow",
                "regulatory", "settlement", "breach", "decline"]

# The "institutional holdings changed" syndication network — press-release
# rewrites about 13F position changes, not bank news.
HOLDINGS_NOISE = re.compile(
    r"sells? \d|buys? \d|position|holdings|short interest|stake|shares (?:of|in)\b",
    re.I)


def tokens(text):
    return [w for w in re.findall(r"[a-z][a-z']+", text.lower())
            if w not in STOP and len(w) > 2]


def table(cur, sql, headers):
    cur.execute(sql)
    rows = cur.fetchall()
    out = ["| " + " | ".join(headers) + " |",
           "|" + "---|" * len(headers)]
    for r in rows:
        out.append("| " + " | ".join("" if v is None else str(v) for v in r) + " |")
    return "\n".join(out)


def main():
    conn = psycopg.connect(os.environ["SUPABASE_DB_URL"])
    cur = conn.cursor()
    p = print

    p("# Ingestion EDA — first pass\n")
    p("Generated by `eda/ingest_overview.py`; all numbers from the live database.\n")

    p("## 1. Text corpus\n")
    p(table(cur, """
        SELECT source, count(*), count(DISTINCT bank_id),
               min(published_at)::date, max(published_at)::date
        FROM raw_item GROUP BY 1 ORDER BY 1""",
        ["source", "items", "banks", "oldest", "newest"]))
    p()
    p(table(cur, """
        SELECT 'gdelt items/bank' AS metric,
               percentile_cont(0.5) WITHIN GROUP (ORDER BY n)::int AS median,
               percentile_cont(0.9) WITHIN GROUP (ORDER BY n)::int AS p90,
               max(n) AS max
        FROM (SELECT bank_id, count(*) n FROM raw_item WHERE source='gdelt' GROUP BY 1) t""",
        ["metric", "median", "p90", "max"]))
    p()
    p(table(cur, """
        SELECT meta->>'language' AS language, count(*),
               round(100.0*count(*)/sum(count(*)) OVER (), 1) AS pct
        FROM raw_item WHERE source='gdelt' GROUP BY 1 ORDER BY 2 DESC LIMIT 6""",
        ["language", "items", "%"]))
    p()
    p(table(cur, """
        SELECT domain, count(*) FROM raw_item WHERE source='gdelt'
        GROUP BY 1 ORDER BY 2 DESC LIMIT 8""", ["domain", "items"]))
    p()
    p(table(cur, """
        SELECT meta->>'form' AS form, count(*),
               round(avg(length(text_excerpt))) AS avg_excerpt_chars
        FROM raw_item WHERE source='edgar' GROUP BY 1 ORDER BY 2 DESC""",
        ["form", "count", "avg excerpt chars"]))
    p()

    p("## 2. Keyword frequencies (GDELT titles)\n")
    cur.execute("SELECT title FROM raw_item WHERE source='gdelt' AND title IS NOT NULL")
    titles = [r[0] for r in cur.fetchall()]
    uni, bi = Counter(), Counter()
    noise = 0
    lex_hits, lex_titles = Counter(), 0
    for t in titles:
        tk = tokens(t)
        uni.update(tk)
        bi.update(" ".join(x) for x in zip(tk, tk[1:]))
        if HOLDINGS_NOISE.search(t):
            noise += 1
        low = t.lower()
        hits = [term for term in RISK_LEXICON if term in low]
        lex_hits.update(hits)
        lex_titles += bool(hits)
    p("Top unigrams: " + ", ".join(f"{w} ({c})" for w, c in uni.most_common(15)) + "\n")
    p("Top bigrams: " + ", ".join(f"{w} ({c})" for w, c in bi.most_common(12)) + "\n")
    p(f"Holdings/13F syndication noise pattern: **{noise}/{len(titles)}"
      f" titles ({100*noise/len(titles):.0f}%)**\n")
    p(f"Risk-lexicon hits: {lex_titles}/{len(titles)} titles"
      f" ({100*lex_titles/len(titles):.1f}%) — " +
      ", ".join(f"{w} ({c})" for w, c in lex_hits.most_common(10)) + "\n")

    p("## 3. Fundamentals features (input to GP thresholds)\n")
    p(table(cur, """
        WITH latest AS (
          SELECT * FROM fact_bank_quarter
          WHERE quarter_end_date = (SELECT max(quarter_end_date) FROM fact_bank_quarter))
        SELECT f.feature, round(min(f.v)::numeric,2),
               round(percentile_cont(0.05) WITHIN GROUP (ORDER BY f.v)::numeric,2),
               round(percentile_cont(0.5)  WITHIN GROUP (ORDER BY f.v)::numeric,2),
               round(percentile_cont(0.95) WITHIN GROUP (ORDER BY f.v)::numeric,2),
               round(max(f.v)::numeric,2)
        FROM latest l CROSS JOIN LATERAL (VALUES
          ('npl_ratio', l.npl_ratio),
          ('loan_loss_allowance_ratio', l.loan_loss_allowance_ratio),
          ('liquidity_ratio', l.liquidity_ratio)) AS f(feature, v)
        WHERE f.v IS NOT NULL GROUP BY 1 ORDER BY 1""",
        ["feature (latest quarter)", "min", "p05", "median", "p95", "max"]))
    p()
    p(table(cur, """
        SELECT 'fact_bank_quarter' AS tbl, count(*) AS rows,
               count(tier1_capital_ratio) AS tier1_nonnull,
               count(total_capital_ratio) AS totcap_nonnull,
               count(securities_unrealized_loss) AS sul_nonnull,
               count(cre_loans) AS cre_nonnull
        FROM fact_bank_quarter""",
        ["table", "rows", "tier1 non-null", "total-cap non-null",
         "unrealized-loss non-null", "cre non-null"]))
    p()

    p("## 4. Distress labels\n")
    p(table(cur, """
        SELECT count(*), sum(distress_within_4q), sum(distress_within_8q),
               round(100.0*sum(distress_within_4q)/count(*), 3)
        FROM fact_bank_quarter""",
        ["bank-quarters", "positive 4q", "positive 8q", "positive 4q %"]))
    p()
    p(table(cur, """
        SELECT CASE WHEN failure_date >= '2017-01-01' THEN '2017+ (GDELT era)'
                    WHEN failure_date >= '2008-01-01' THEN '2008-2016'
                    ELSE 'pre-2008' END, count(*)
        FROM fact_distress_event GROUP BY 1 ORDER BY 1""",
        ["era", "failures"]))

    conn.close()


if __name__ == "__main__":
    main()
